services:
  postgres:
    profiles:
      - backing_service
    image: postgres:13.5
    container_name: nest-authorization-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    env_file:
      - ./.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: